name: payflow_2
description: NLW TOGETHER

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  firebase_core: ^1.3.0
  google_sign_in: ^5.2.4
  google_sign_in_web: ^0.10.0
  shared_preferences: ^2.0.6
  google_ml_kit: ^0.7.3
  camera: ^0.9.4+16
  image_picker: ^0.8.4+11
  font_awesome_flutter: ^9.1.0
  flutter_masked_text2: ^0.9.1
  firebase_database: ^9.0.9
  cool_alert: ^1.1.0
  animated_card: ^2.0.0
  syncfusion_flutter_charts: ^20.1.47

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.2
  
flutter_icons:
  ios: true
  image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true



 
  assets:
    - assets/images/